site_name: Records
site_description: Documentation for Donovan's Programming Journey
site_author: Donovan Zhong

repo_url: https://github.com/20dzhong/20dzhong-mkdocs.git

nav:
  - Home: index.md
  - Java:
    - Basics: javaBasic.md
    - Inheritance: inheritance.md

  - Python:
    - Etc: pythonExtra.md

  - C++/C:
    - Basics: cBasics.md

  - Machine Learning:
    - Basics: mlBasic.md

theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: false
  language: en
  feature:
    tabs: false
  palette:
    primary: blue grey
    accent: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/gothub.png'
  favicon: 'images/gothub.ico'
