site_name: Records
site_description: Documentation for Donovan's Programming Journey
site_author: Donovan Zhong

repo_url: https://github.com/20dzhong/20dzhong-mkdocs.git

nav:
  - Home: index.md
  - Java:
    - Basics: javaBasic.md
    - Inheritance: inheritance.md

  - Python:
    - Lambdas: pyLambda.md
    - Etc: pythonExtra.md

  - C++/C:
    - Basics: cBasics.md

  - Machine Learning:
    - Basics: mlBasic.md

  - Data Structures:
      - Hashmaps: javaHashmap.md

  - Github: git.md

theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: false
  language: en
  feature:
    tabs: false
  palette:
    primary: blue grey
    accent: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/gothub.png'
  favicon: 'images/gothub.ico'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics: ['UA-90285378-1', 'auto']
